### ISSUE TITLE
nginx default SERVER_NAME == '_'  crashing interface 

### ISSUE THREAD

**Issue by walkeralencar** [phpmongodb/phpmongodb#10]
when using nginx it crash interface because Theme cant get right SERVER_NAME

**Comment by phpmongodb** [comment]
Sorry for late reply but i am also using nginx its working fine. kindly please explain a little bit for the scenario

**Comment by walkeralencar** [comment]
whend u use nginx with multiple vhosts, dont exist variable: $_SERVER["SERVER_NAME"], in that case you will need to get: $_SERVER["HTTP_HOST"]

c892693 fix that ;)

**Comment by lostsnow** [comment]
why not use `HTTP_HOST` instead of `SERVER_NAME`

> <http://stackoverflow.com/questions/2297403/http-host-vs-server-name>
> The `HTTP_HOST` is obtained from the HTTP request header and this is what the client actually used as "target host" of the request. The `SERVER_NAME` is defined in server config.
