### ISSUE TITLE
Static assets not downloaded correctly

### ISSUE THREAD

**Issue by margru** [phpmongodb/phpmongodb#17]
All links to static assets (CSS, JS) in the index page starts with `http://localhost/` regardless of the address the application is really running. Thus, no asset files are downloaded and the application is not working correctly. Might be there a configuration error or a web server settings error (I'm using nginx)? Or is it supposed to run only from the localhost?

**Comment by phpmongodb** [comment]
Hi 
Sorry for late reply
Can  you share your url how your running project
In My local Invironment i am also using nginx

Suppose your url is http://localhost/phpmongodb/ then static content will be 
<link rel="stylesheet" type="text/css" href="http://localhost/phpmongodb/application/themes/default/bootstrap/css/bootstrap.css">
Or url is 
http://phpmongodb.loc/ static content will be
 <link rel="stylesheet" type="text/css" href="http://phpmongodb.loc/application/themes/default/bootstrap/css/bootstrap.css">
Thanks

**Comment by margru** [comment]
Hi,
I don't see the lines what the content should be in your previous post. However, the URL is `http://server-name/phpmongo/`.

**Comment by phpmongodb** [comment]
I have just checked in my local system http://localhost/nanhe/phpmongodb/ it is working fine.
if you have deployed public area then please share your url.
Thanks
Nanhe

**Comment by margru** [comment]
Unfortunatelly, the URL is not public and only accessible via VPN so I cannot share it. I believe that URLs starting with `http://localhost` are working fine but if you try to access the phpmongodb from another computer with no HTTP server running on it, it will fail when downloading the static assets...

Here is a part of the header of `index.html` which I got when accessing the `http://server-name/phpmongodb/`:

```html
<link rel="stylesheet" type="text/css" href="http://localhost/phpmongodb/application/themes/default/bootstrap/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="http://localhost/phpmongodb/application/themes/default/css/style.css?v=1441884937 ">
<link rel="icon" href="http://localhost/phpmongodb/application/themes/default/images/favicon.ico" type="image/x-icon" />
<script src="http://localhost/phpmongodb/application/themes/default/js/jquery-1.8.1.min.js" type="text/javascript"></script>
```

You can see the links to `http://localhost/...` and it should be `http://server-name/...` instead.

The issue won't appear if you are trying that on a computer which is running an HTTP server with `phpmongodb` installed as the links to `http://localhost/..` are then valid and the static assets are loaded from the local computer (not from the remote server).

**Comment by margru** [comment]
Well, I have another finding - if the `phpmongodb` is running in `http://some-public-name.com/phpmongodb/`, it's working, but if it's (like in my case) `http://some-local-server-name/phpmongodb`, it's not. I have just tried that on two different machines (one publicly available, the second one is hidden) with a clean git clone of the `phpmongodb`. It's really weird...
