### ISSUE TITLE
xss vulnerability

### ISSUE THREAD

**Issue by mousavian** [phpmongodb/phpmongodb#24]
At first glance, this project is vulnerable to XSS attacks. I guess it is risky to use this package in production unless some security researchers take a look in the source code.

I have wrote a quick fix for one I've found and will make a pull request shortly.

![capture](https://cloud.githubusercontent.com/assets/317322/13246015/f33602f8-da4b-11e5-985a-beda6a95a6ad.PNG)

**Comment by phpmongodb** [comment]
@mousavian : XSS is issue fixed please update and check.
