### ISSUE TITLE
Update to new PHP MongoDB driver

### ISSUE THREAD

**Issue by laurin1** [phpmongodb/phpmongodb#26]
The one used is deprecated. Any change of upgrading to the new driver?

**Comment by phpmongodb** [comment]
Hi Laurin
I am not clear what your are saying please elaborate.

Thanks

**Comment by laurin1** [comment]
"To make things right, you must install php_mongo module. Here for installation documents on PHP.net."

This application uses the PHP Mongo driver (http://php.net/manual/en/mongo.setup.php), which is deprecated and has been replaced by the PHP MonogDB drive (http://php.net/manual/en/set.mongodb.php) and extended by the PHP MongoDB Library (https://github.com/mongodb/mongo-php-library).

**Comment by phpmongodb** [comment]
Thanks for your support.

**Comment by code-fury** [comment]
is it fixed?

**Comment by phpmongodb** [comment]
code-fury : Yes but i want publish both version please suggest what will be good way.

**Comment by code-fury** [comment]
Can you pack 2 versions in this repo so people can chose which to use

**Comment by phpmongodb** [comment]
Thank you for your support.
Do you want other feature if you have any idea please suggest.

**Comment by devsibwarra** [comment]
Is it possible to re-organize the code to support both versions, preferring the newer PHP MongoDB?  If not, I'd suggest creating a branch or tag supporting the older `mongo` module and point to it in README.md, then update master with support for the new `mongodb` module.

**Comment by RobbieLePommie** [comment]
I have a forked version https://github.com/RobbieLePommie/phpmongodb that supports only the newer drivers.

Quick warning: very quickly hacked to get the new drivers in; I've not (yet) optimised anything to benefit from the newer drivers and not all features have been tested. But allows me to do the basics.

**Comment by phpmongodb** [comment]
@RobbieLePommie 👍
