### ISSUE TITLE
　Cannot create databases

### ISSUE THREAD

**Issue by terrylinooo** [phpmongodb/phpmongodb#27]
After submitting database name in the blank field, and then show me the success message, but it is not created successfully.

ps. I logged in as the super user, and I can create databases by command line.

**Comment by phpmongodb** [comment]
@terrylinooo : Please share your mongoldb version and your operating system.

**Comment by terrylinooo** [comment]
Here is screenshot of the information, thanks for help.
![mo](https://cloud.githubusercontent.com/assets/11989371/16609011/0819068e-4383-11e6-9f17-1abc0616b194.png)

**Comment by phpmongodb** [comment]
@terrylinooo Tank you for your valuable feedback issue resolved you can now crate database.
