### ISSUE TITLE
Undefined property error when clicked on Databases link

### ISSUE THREAD

**Issue by shairya** [phpmongodb/phpmongodb#29]
Notice: Undefined property via __get(): databases in /var/www/html/phpmongodb/system/Session.php on line 17 in /var/www/html/phpmongodb/system/Data.php on line 24
![screenshot from 2017-05-11 19 49 38](https://cloud.githubusercontent.com/assets/12731641/25954142/02e9d67c-3683-11e7-8b58-251452ab9088.png)

**Comment by phpmongodb** [comment]
Hi @shairya 
Issue resolved please git pull.
