### ISSUE TITLE
Can't connect to my mongodb instance (not localhost)

### ISSUE THREAD

**Issue by jrborbars** [phpmongodb/phpmongodb#3]
I have a server that have a mongodb instance installed and working properly (accessible from CLI). My client machine have a nginx/php-fpm with mongodb driver installed (1.6.0-dev, from phpinfo() ) and all works fine. But I installed phpmongodb on my client machine (to access the server), and have no access to the mongodb instance. I have followed the installation instructions on github, without success.

The message error:
#########################################
Failed to connect to: 1:27017: Invalid argument

config.php
#########################################
   public static $server=array(
        'name' => "MyMongoServer",
        'server'=> false,
        'host' => "myNetworkIp",
        'port'=>"27017",
        'timeout'=>0,
    );
    public static $authentication = array(
        'authentication'=>true,
        'user' => 'admin',
        'password' => 'admin'
    );
    public static $authorization = array(
        'readonly'=>true,
    );

Both machines have arch linux installed, and (I checked) iptables are empty on both (for development).

What I'm doing wrong? Any Ideas?

Best regards,

**Comment by jrborbars** [comment]
Sorry about the gap. No user and password, hostname ok and port is ok too.
MongoDB 2.6.6, on arch x86_64, kernel 3.17.6-1, HHVM 3.4.2.
Tested too on MongoDB 2.6.6 on arch i386 with kernel 3.17.6-4, PHP 5.6 and PHP-FPM.
 How can I test without your software, to make the right assumptions? Best regards.

**Comment by phpmongodb** [comment]
Sorry for late reply
I will try resolve your problem in morning
Thanks for your support
Thanks & Regards
Nanhe kumar

**Comment by phpmongodb** [comment]
Sorry for late reply but it working fine in test environment
