### ISSUE TITLE
Import Not working with User Login

### ISSUE THREAD

**Issue by netwavetech** [phpmongodb/phpmongodb#7]
When using a user that has the following roles on the database:

'roles': [ 'readWrite', 'dbAdmin', 'userAdmin', 'clusterAdmin' ]

The import to collection function says: Note: unauthorized

**Comment by netwavetech** [comment]
Also when using the insert --> json box, I get invalid json as an error, even though I am inputting a valid json string like:

{
    "test": "her",
    "lost": "me"
}

**Comment by netwavetech** [comment]
It also appears editing an entry via JSON results in Not authorized.  But using the array  editing works 100% fine.  What are we missing?

**Comment by netwavetech** [comment]
When logged in as the admin (root) user of the mongo server,  JSON inputs work, but the import still does not. Get the following error on import:

Note: exception: JavaScript execution failed: SyntaxError: Unexpected token }

Hope this helps

**Comment by netwavetech** [comment]
While this project seems to be abandoned.   All of the above issues are cause of the use of the "execute" command in several locations.  These sections will have to be 100% re-written for this to work with end user logins and MongoDB 2.6+

**Comment by phpmongodb** [comment]
@netwavetech 

Hi i have just created and test import is working fine.

db.createUser( { "user" : "user1",
                 "pwd": "user1",
                 "roles" : [ { role: "clusterAdmin", db: "admin" },
                             { role: "readAnyDatabase", db: "admin" },
                             "readWrite"
                             ] },
               { w: "majority" , wtimeout: 5000 } );

Please share how you are creating user.

**Comment by phpmongodb** [comment]
System information

PHP version 	5.5.9-1ubuntu4.8
Web server 	nginx/1.4.6
MongoDB Version 	2.6.9

**Comment by netwavetech** [comment]
We are using another php script to create users using the following:
$userperm = "readWrite"; 
 $userDBAdmin = "dbAdmin";
 $usersAdmin = "userAdmin";
 $clusterAdmin = "clusterAdmin"; 
	
	$db = $conn->$db_name;
	sleep(2);
	$collection = $db->selectCollection("system.users");
	$collection->insert(array('user' => $username, 'pwd' => md5($username . ":mongo:" . $newpass), 'roles' => array($userperm, $userDBAdmin, $usersAdmin, $clusterAdmin)));

System information:
OSmongo CentOS release 6.6 (Final)
PHP version 	5.3.29
Web server 	Apache/2.2.29 (Unix)
MongoDB Version 3.0.4

Also tried on a 2.6.9 install.  Same results.  Funny thing is if I modify the code in system/Model.php under the insert function to use json_decode and then an insert,  the json insert works fine. However the import doesnt, because of how you are reading the file in the import loop.

if ($fromat == 'json') {
            
            	$a = json_decode($a, true);
            	return $this->mongo->{$db}->{$collection}->insert($a);
                //$code = "db.getCollection('" . $collection . "').insert(" . $a . ");";
                //return $this->mongo->{$db}->execute($code);
                
            } 
            
            else {
                return $this->mongo->{$db}->{$collection}->insert($a);
            }


As I said, the excute command has been depreciated in 2.6 and looks like completely removed in 3.0+

**Comment by netwavetech** [comment]
Also, can not use the readAnyDatabase Role, as it breaks security between databases.

**Comment by phpmongodb** [comment]
Have any problem in PHPmongoDB Then i can help.

**Comment by netwavetech** [comment]
Fine we will look at re-writing these two sections so that they can work with proper security and not require readAnyDatabase Role, as well as remove the excute command throughout since it has been depreciated and removed in 3.0+

**Comment by phpmongodb** [comment]
Thanks for your suggestion i will fix this issue

**Comment by netwavetech** [comment]
Any update on making this work with Mongo 3.x without having to have readAnyDatabase, so security can be enforced.
