### ISSUE TITLE
Doesn't work under HTTPS

### ISSUE THREAD

**Issue by c00** [phpmongodb/phpmongodb#8]
Under Debian Wheezy PHP5 I installed the package. 
The application is trying to figure out whether to use HTTP or HTTPS, and it doesn't succeed. The page loads but without any CSS and all links are shot as well. Looking at the source I see this for the CSS files:

```
<link rel="stylesheet" type="text/css" href="<br />
<b>Notice</b>:  Undefined variable: serverProtocol in <b>/some/path/phpmongodb/system/Theme.php</b> on line <b>37</b><br />
slocalhost/phpmongodb.com:443/phpmongodb/application/themes/default/bootstrap/css/bootstrap.css">
```
Which should be something along the lines of:

    <link rel="stylesheet" type="text/css" href="https://localhost/phpmongodb/phpmongodb/application/themes/default/bootstrap/css/bootstrap.css">

Note that there's an `S` at the beginning of the URL that shouldn't be there, while the HTTP is replaced for an error message. The script links also have an `S` that shouldn't be there and no protocol.

**Comment by c00** [comment]
I think I created a pull request with the fix. I'm new to Github so forgive me if that went wrong. However the fix is working for me on both HTTP and HTTPS. 

[Pull request](https://github.com/phpmongodb/phpmongodb/pull/9)

**Comment by phpmongodb** [comment]
issue fixed your branch merged successfully 
Tthanks
